# Generated by Django 3.2.7 on 2021-09-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210913_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='korean_name',
        ),
    ]
